FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build -- --configuration production

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist/centro-ecuestre-reservas/browser ./dist

EXPOSE 8082

CMD ["serve", "-s", "./dist", "-l", "8082"]
