services:
  frontend:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: caballos-frontend
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
