FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build -- --configuration production

FROM node:20-alpine

WORKDIR /app

RUN npm install -g http-server

COPY --from=builder /app/dist/centro-ecuestre-reservas/browser ./dist

EXPOSE 8082

CMD ["http-server", "./dist", "-p", "8082", "-c-1"]
